### ISSUE TITLE
Support for compiled methods

### ISSUE THREAD

**Issue by kayhayen** [ronaldoussoren/pyobjc#502]
**Describe the bug**

In Nuitka, we compile code that is normally a Python function to compiled functions. These behave equally well to standard Pythons function and are very compatible. They are also derived types from un-compiled ones.

On the C level, they are also methods, compiled methods, and functions, compiled functions.  The code in `pyobjc` currently does use `PyMethod_Check` and `PyFunction_Check` in sections. It then uses `PyMethod_Self` which of course also wouldn't work with compiled methods (it may assert against it, not sure).

The solution is fairly easy, you need to use `PyObject_IsInstance` on the respective types, and attribute lookups, e.g. `__self__` rather than the dedicated methods.

The issue is that e.g. code as simple as this will fail to work:

```
import objc

v = objc.registerCFSignature('CFAllocatorRef', b'^{__CFAllocator=}', 2)
print(v)
```

If you wanted to reproduce it, `pip install nuitka ` and `python -m nuitka --run --standalone Mini.py` should do it for you. It complains about a class not being assigned where it was expected. Likely a method that the current code fails to extract.

My question is now, would you accept a PR to change the code to remove this limitation. The code change I can make can come in two flavors. Adding an extra `PyObject_IsInstance` check and branch duplicating the CPython specific code. Or one that replaces it with that.

As you can imagine, plenty of Python software depends on pyobjc, so we are willing to do the upstream change, or at least provide the input, if you are willing to carry it. I did this e.g. with PySide in the past.

Hope to be hearing from you.

**Comment by ronaldoussoren** [comment]
For my understanding: Are Nuitka compiled Python functions instances of a subclass of the built-in function type?

That is:

```python
import types

def spam():
    pass

assert isinstance(type(spam), types.FunctionType)
assert type(spam) == types.FunctionType # True for CPython, false for Nuitka
```

**Comment by ronaldoussoren** [comment]
A second question: Do instances of a Nuitka-compiled Python function still have an associated code object?  PyObjC uses the code object of function tot automatically determine a default signature for methods (that is, the effective Objective-C prototype for methods with and without ``return value`` in their implementation is different.

**Comment by ronaldoussoren** [comment]
And finally: Nuitka is an interesting project and I'll look into fixing incompatibilities where possible.

**Comment by ronaldoussoren** [comment]
>  It then uses `PyMethod_Self` which of course also wouldn't work with compiled methods (it may assert against it, not sure).

That's technically a bug in Nuitka. If ``PyMethod_Check(value)`` is true, then ``PyMethod_Self(value)`` should work and should have the same result as ``PyObject_GetAttrString(value, "__self__")``. That said, PyObjC's usage of ``PyMethod_Self`` is not a performance critical part of the code and switching to ``PyObject_GetAttr`` here should be fine.

Don't bother with a pull request, the master branch is currently unstable, I'll look into this once it is stable again.

**Comment by kayhayen** [comment]
Regarding your first question, both should be true in Python code. Nuitka hooks the type comparison to make sure of the later, which is kind of a hack, but Python code is supposed to not ever have an issue from that.

For the second question, having a code object is of course required. But `__code__` will have empty bytecode, but arguments work. It is good enough to pass `inspect` tests of all kinds. The only real incompatibility there is when it comes to copying functions, and trying to assign `__code__` from another function, that is not allowed.

**Comment by kayhayen** [comment]
But in C it's different, equality of types is not overloaded there, `PyMethod_Check` is *not* true for compiled methods.

**Comment by ronaldoussoren** [comment]
> Regarding your first question, both should be true in Python code. Nuitka hooks the type comparison to make sure of the later, which is kind of a hack, but Python code is supposed to not ever have an issue from that.
> 
> For the second question, having a code object is of course required. But `__code__` will have empty bytecode, but arguments work. It is good enough to pass `inspect` tests of all kinds. The only real incompatibility there is when it comes to copying functions, and trying to assign `__code__` from another function, that is not allowed.

An empty ``__code__`` could be a problem for PyObjC, although that depends on details of the arm64 and x86_64 calling conventions on macOS. That's something I haven't seriously looked into yet, but in practice this likely isn't a problem.

Given this class definition:

```python
import Foundation

class MyObject (Foundation.NSObject):
     def method1(self):
            pass

     def method2(self):
           return 42
```

PyObjC will dynamically generate an Objective-C class with two methods and derives the method signature from the bytecode (assuming the methods aren't overriding existing methods), in this case the class interface is something like:

```objective-c
@interface MyObject: NSObject
-(void)method1 {
}
-(NSObject*)method2 {
  return [NSNumber numberWithInt:42];
}
@end
```

Note that the first method "returns" ``void`` while the second returns ``NSObject*`` because the bytecode for the former doesn't contain an explicit return statement while the second does.

**Comment by ronaldoussoren** [comment]
> But in C it's different, equality of types is not overloaded there, `PyMethod_Check` is _not_ true for compiled methods.

I'll have to stare at the generated C code from Nuitka to fully understand how to fix this properly on my end.  And to be honest that might result in dropping most ``PyMethod_Check`` paths in my code entirely, those were in definitely needed in Python 2.7 where "unbound method" objects were a thing, but that's no longer true in Python 3.

**Comment by ronaldoussoren** [comment]
I currently get (using master branch):

```
Traceback (most recent call last):
  File ".../pyobjc-core/error.dist/error.py", line 3, in <module>
  File ".../pyobjc-core/error.dist/objc/_convenience.py", line 78, in makeBundleForClass
TypeError: Cannot calculate default method signature
```

That's due to this function:

```python
@register
def makeBundleForClass():
    cb = currentBundle()
    
    def bundleForClass(cls):
        return cb

    return selector(bundleForClass, isClassMethod=True)
```

In particular, the call to ``selector`` at its return statement. The ``bundleForClass`` argument is a callable that passes neither ``PyFunction_Check`` nor ``PyMethod_Check`` and ``pysel_default_signature`` in ``pyobjc-core/Modules/objc/selector.m`` cannot calculate a default signature. 

That's related to [my earlier comment](https://github.com/ronaldoussoren/pyobjc/issues/502#issuecomment-1280022404), I have to think a little about a good fix. Luckily this is not a hot path and I can easily add some more code that works with Nuitka.

I have a quick fix for this on my machine that ensures that the code example you shared now works when compiled using Nuitka. That fix is incomplete though, I'll look into a more complete fix.

**Comment by ronaldoussoren** [comment]
As expected more work it needed. When I run the pyobjc-core unit tests with Nuitka I get an error when loading the test modules:

```
.../runtests.dist/PyObjCTest/test_hidden_selector.py", line 23, in <module PyObjCTest.test_hidden_selector>
TypeError: Sorry, cannot create IMP for instances of type compiled_function
```

That's a similar issue as the one I fixed in changeset a8aa42e108b4c688e23d9b03c2c3f0ff4caa27dd, but in a different part of the codebase.

**Comment by ronaldoussoren** [comment]
Note to self: Nuitka-compiled modules have a ``__compiled__`` attribute that can be used to adjust code paths (in particular to tweak some tests)

**Comment by ronaldoussoren** [comment]
Current plan is to  replace ``PyFunction_*`` and ``PyMethod_*`` by internal APIs in PyObjC that perform similar functionality through the Python interface (e.g. using ``PyObject_GetAttrString(value, "__code__")`` instead of ``PyFunction_GetCode(value)``.  Likewise introduce APIs for accessing attributes instead of peeking at them directly. Basically as suggested by @kayhayen. 

Usage of these APIs is generally in slow paths, and this implementation strategy is close enough to current behaviour (although some refcount code needs to be update because the current APIs can return borrowed references and the new API will use strong references.

**Comment by kayhayen** [comment]
Seeing that you used `PyMethod_Self` to get the instance, I am assuming, you might need to handle them still special. I think methods do not have a `__code__` object themselves, the `self` is very special in Python in that way, and e.g. cannot be passed as a keyword argument. 

This may not affect you, but in some cases, unbound methods still exist in Python3, they are used when assigning methods, but no longer during the call, where Python core avoids creating them (emulating an old optimization of Nuitka), and so Nuitka still has to have them. And they might end up everywhere, for code like this `a = someClass.some_method` which would be an unbound method, that can be called or used everywhere.

From your `__compile__` comment, I took note, that this is something I kind of like dislike. Right now, users cannot select on th function level, if it is compiled, but I believe I am adding `__compiled__` to compiled function as a detection method. Since that is a global constant, there is no harm in having that attribute.

That said, to detect a function without bytecode checking the bytecode attribute of `__code__` is what I would love to see happening. And your example was simple, and we are learning about each other's project here. So this is not only a bridge, but you also do a kind of JIT compilation there. How far does it go. Do you react to constants only? Or to more complex code constructs as well?

Nuitka happens to already have specialized handling for constant returning function bodies, so they share the C code, for reduce code cache usage, and compilation scalability mostly. If the compiled functions exposed this constant, in an optional attribute `__constant_result__` would that help you there, or is this more general?

In Nuitka, returning `None` is added at the end of the function body, so there is no real `void` function. However, if it is known what the function result is, this could be exposed as well, and also if it is always a default return. This would probably have to be indicated by something like another attribute to be added.

But ultimately, what you ought to be able to always do is to vector call the compiled function with the arguments, if it gets  more complex. That would be terrible for performance. Am I right in assuming that this is code that you consider running e.g. per pixel, or something like that, and that is why you are JITing rather than merely bridging?

Very happy to see you pick this up, seems we can get this to work relatively easy.

**Comment by ronaldoussoren** [comment]
The ``__compile__`` comment is a reminder how I can detect Nuitka compiled code and is intended to be used in my tests to be able to tweak the behaviour of tests that behave differently (e.g. the automatic calculation of a default method signature that I mentioned earlier).

PyObjC does not have a JIT compiler, it uses libffi to call (Objective-)C code and be called from (Objective-)C code. Similar to ctypes in the stdlib, but targeted at Objective-C interoperability and with a different interface. I'm slowly working on reducing the overhead of this layer, but I hope this won't end with a JIT. Projects like yours or cython can be used for AOT compilation and that should be good enough for performance critical code.  I'm already using the vectorcall API with new enough versions of Python because that's a clear performance improvement.

PyObjC does look at function bytecode, but only to detect if the bytecode contains the code for a return statement with a value (or rather a return statement that's not "return" or "return None"). For those function the bridge assumes that the return value of the Objective-C equivalent should be "void".   Some kind of feature in Nuitka that helps replicate this logic for compiled functions would be helpful.  The easiest on my end would be a return statement in the code object attached to the compiled function when the original function contains such as statement (juist having the bytecode equivalent for "return 1" would be good enough for me), but a custom attribute would also work.

The relevant C code (``buffer`` is a ``Py_buffer`` for the bytecode, ``result`` is a C string with an Objective-C type encoding with the return value type in ``result[0]`` which is initialised with`` _C_VOID``):

```C
        for (i = 0; i < buf.len; ++i) {
            int op = ((unsigned char*)buf.buf)[i];
            if (op == LOAD_CONST && ((unsigned char*)buf.buf)[i + 1] == 0
                && ((unsigned char*)buf.buf)[i + 2] == 0) {
                was_none = 1;
            } else {
                if (op == RETURN_VALUE) {
                    if (!was_none) {
                        result[0] = _C_ID;
                        break;
                    }
                }
                was_none = 0;
            }
            if (op >= HAVE_ARGUMENT) {
                i += 2;
            }
```

This scans for. ``LOAD_CONST N; RETURN_VALUE``, with ``N`` != 0, as ``None`` is stored at index 0 in the locals array by default. I have to check the code is still valid with changes in Python 3.11 and especially in 3.12. 

That said,  I'm not 100% sure if this functionality is really necessary at this time. With some luck the calling conventions for C functions returning ``void`` and a pointer are close enough to not cause problems. I'll have to check Apple's documentation on the calling conventions for x86_64 and arm64 to be sure.

**Comment by kayhayen** [comment]
I think all ABIs tend to dedicate a register for function return values, and therefore `void` and `int` return can be done according to wrong declarations, and still "work", so if it was only that, it would be good. From my memory of ARM Linux ABI also uses a register for return value, but I usually don't care much about this. Luckily your ABI targets are very limited, currently only 2 I assume, and therefore easy to test if they all do.

The above code in that case would then be unnecessary.


When you wrote

```
@interface MyObject: NSObject
-(void)method1 {
}
-(NSObject*)method2 {
  return [NSNumber numberWithInt:42];
}
```

Were you suggesting that the return value is actually created for that function too. How does this work when there are side effects? Say 

````
def method2(self):
   something_else()
   return 42
```

I am going to add the attributes now, so you could use them if you wanted to do that kind of optimization. I didn't see the above code check for static return values, maybe that is elsewhere? And also how does above code react to this kind of code:

````
def method2(self):
  if cond:
      return True
  elif other_code:
      return False
  else:
      return None
```

**Comment by ronaldoussoren** [comment]
For ``method2`` there is a return with a value, therefore the bridge assumes that an object is returned in Objective-C.  If the code hits the 3th return at runtime the C proxy will return a NULL pointer.

I don't look for static returns at all. The bridge is "just" a layer that converts between Python and Objective-C, and vice versa. For calls from Objective-C to Python I'm using a libffi closure that translates the C argument values to Python objects, then calls the Python callable using the PyObject_Vectorcall and finally convert the return value back into the right C type.

**Comment by kayhayen** [comment]
I see, so if you can drop that `void` logic, or just assume `NSObject` in case of compiled functions you are probably good already, the new attribute would allow you to do it, but it's not a priority. For me right now, working correctly would be most important, but I got this to work:

```
def f1():
    return 42

def f2():
    return x

exec("""
def g():
    pass"""
)

print("f1 is", getattr(f1, "__compiled__", None))
print("f1 is constant returner", hasattr(f1, "__compiled_constant__"))
print("f2 is", getattr(f2, "__compiled__", None))
print("f2 is constant returner", hasattr(f2, "__compiled_constant__"))
print("g is", getattr(g, "__compiled__", None))
print("g is constant returner", hasattr(g, "__compiled_constant__"))
```

```
Nuitka:INFO: Launching 'Mini.cmd'
f1 is __nuitka_version__(major=1, minor=2, micro=0, releaselevel='candidate', standalone=False, onefile=False)
f1 is constant returner True
f2 is __nuitka_version__(major=1, minor=2, micro=0, releaselevel='candidate', standalone=False, onefile=False)
f2 is constant returner False
g is None
g is constant returner False
```

So if you wanted to handle constant only returns, you could. They also have simple bytecode I assume, so it wouldn't have to be Nuitka only. The `__compiled_constant__` is merely exposing the constant value of that single return value, as it's going to be done by the C code. The constant return value in case of Nuitka can of course depend on `sys.version` and the like, so that's going to be more cases still.

Also it kind of illustrates, with the newly added `__compiled__` for function objects, un-compiled and compiled methods can be mixed in a module. Disregard the lack of statically optimizing `exec` statements by Nuitka here.

I am including this on my `factory` branch right now (see https://nuitka.net/doc/factory.html) but from what you wrote, you may not have a need for that at all to get things to work. If you feel that I should look at test results, let me know, and I will put it the change on the hotfix branch for 1.1.6 as well, so it will be in my next stable update as well.

**Comment by ronaldoussoren** [comment]
So close...

```
env PYTHONPATH=$PWD ../workenv/bin/python3 -mnuitka --run --standalone --include-package=PyObjCTest --include-package-data=PyObjCTest /Users/ronald/Projects/pyobjc-8/pyobjc-core/Tools/runtests.py
.... [ 2600 mostly successful test results ] ...
test_draining_outer_pool (PyObjCTest.test_internals.TestReleasePoolManagement) ... ERROR
Exception ignored in: <OC_ReleasePool_Recorder objective-c instance 0x0>
Traceback (most recent call last):
  File "/Users/ronald/Projects/pyobjc-8/pyobjc-core/runtests.dist/unittest/case.py", line 613, in run
objc.UninitializedDeallocWarning: leaking an uninitialized object of type OC_ReleasePool_Recorder
zsh: segmentation fault  env PYTHONPATH=$PWD ../workenv/bin/python3 -mnuitka --run --standalone   
```

The 2600 tests that were successful include a large number of tests for calling Objective-C methods and calling Python methods from Objective-C. 

I've yet to fully debug this, but the following is a reproducer:

```
import objc
from objc import super

NSObject = objc.lookUpClass("NSObject")

class Record (NSObject):
    def initWithCallback_(self, callback):
        self = super().init()
        #self = self.init()
        self.callback = callback
        return self
        
    def doit(self):
        self.callback()
        
o = Record.alloc().initWithCallback_(lambda: print("hello"))

o.doit()
```

Replacing ``super().init()`` by ``self.init()`` fixes the error. Actually reproducing this requires using changeset fec7ae937b4b8327417e38a4927886ada0aae977.

**Comment by ronaldoussoren** [comment]
@kayhayen: does Nuitka do anything special with calls to super?  And/or does Nuitka replace (parts of) the built-in PySuper_Type?

PyObjC contains a custom implementation of ``super`` (as ``objc.super``) which is a subclass of ``PySuper_Type``. The custom super is needed because the built-in one has assumptions that aren't true for PyObjC's classes.

Note that I can reproduce the error without using PyObjC:

```python
import builtins
class super (builtins.super):
    def __getattribute__(self, name):
        return builtins.super.__getattribute__(self, name)

class Object:
    def init(self):
        return self


class Record (Object):
    def initWithCallback_(self, callback):
        self = super().init()
        self.callback = callback
        return self

    def doit(self):
        self.callback()

o = Record().initWithCallback_(lambda: print("hello"))

o.doit()
```

This works with plain Python 3.10.8, but fails when compiling the script with Nuitka. Nuitka was installed from pip, version info:

```
1.1.5
Commercial: None
Python: 3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: Unknown
Executable: /Users/ronald/Projects/pyobjc-8/workenv/bin/python3
OS: Darwin
Arch: arm64
```

**Comment by kayhayen** [comment]
@ronaldoussoren the `super` needs special handling in Nuitka, because it needs to capture `__class__` from the outside context, but there won't be a cell object to use for it. I will look into this. Right now, what I suspect is happening, is that `super()` does not get optimized, when it's a name assigned in the module, but that is not going to fly, and real super without arguments is going to hate life very hard. But let me research this more.

**Comment by kayhayen** [comment]
Yes, it gives `RuntimeError: super(): arg[0] deleted` and uses the built-in super, which will then work very badly in your `super` class, which will be used in your example. It has tried to find the `self` argument of the calling function there.

**Comment by kayhayen** [comment]
I was going to suggest to use the old style, but I don't know if that is anything near acceptable to you. I saves poor `super` to find out information that the code already allows to write up statically. Nuitka has code to resolve it at compile time, but that code will never run, `super` has any assignment in the module.

The code to defeat, can be tricked. I think, what I can do is, on top of syncing the line number, etc. when calling an "unknown" function, when that is named `super`, it could mangle `f_localsplus` to what is needed. So, if Nuitka had an intact `f_localsplus[0]` in its frame object, with `self` and a closure cell `__class__, it would do the correct thing. The later is kind of hard to do.

The other solution would be to ignore your assignment, and simple do that optimization for `super` at least anyway, but keep the `super` lookup. I will get back to you with some sort of solution.

**Comment by ronaldoussoren** [comment]
Using the old style isn't really acceptable, the modern form is much more convenient.   Note that ignoring the the assignment to super is not correct, ``objc.super`` is really needed.  I'm still hoping for a better solution in CPython itself, but that will take time (if it happens at all).

Sorry about turning your easy question about supporting Nuitka in PyObjC into a major endeavour on your end :-(.

**Comment by kayhayen** [comment]
That's perfectly fine. I will at first make sure that monkey patching `super` is going to work, which I take may not help you specifically at all, because you want this to be a local effect, right. Then, I need to experiment a bit with what's easier for me, to change the frame object so original `super.__init__()` works for me, or just to ignore safety precautions, maybe with a bit of a check, where Nuitka would treat an assignment to a class `super` differently. It's not dramatic. And I like that we both get to improve our code bases. :)

**Comment by kayhayen** [comment]
So, I got monkey patch built ins of `super` to work. Also no longer replicating `super` implementation, that is not very useful anyway. And for your reproducer, I got it work, but with a kind of crude hack. It will just ignore writes to the module variable `super` and convert it to the built-in, doing the static re-formulation to the 2 arguments form on the fly. However, when calling it, that helper code now does only use the `super` built-in when there is no module variable in the module dictionary, with that it is just working. I am going to push it soon, but I will need to wait for internal CI of mine to run all the CPython test suites, to be sure it's not messing anything up for them.

In theory, this should only have a negative effect, if somebody were to want to see `__init__` calls without arguments in a super class, rather than pre-resolved ones.

**Comment by kayhayen** [comment]
So, looks fantastic in my CI, the factory branch should be good, and I selected the two `super` related improvements, and even adding the `__compiled__` and `__compiled_constant__` change for hotfix/1.1.6 branch, which I will be pushing out as a stable release, once I completed checks for more reports that might go in quickly. With that I believe, I am set from my side of things, I will probably add a hint in Nuitka to the compiling user, if you let me know which version of `pyobj` is getting your changes, then I can complain about unsupported version.

**Comment by ronaldoussoren** [comment]
My changes will be in PyObjC 9.0. Current plan is to release that sometime in the next week.

Are your changes in the current version of https://github.com/Nuitka/Nuitka/archive/develop.zip?  If they are I can check on my end if everything works as expected.

**Comment by ronaldoussoren** [comment]
I've released PyObjC 9.0 with these fixes.

**Comment by kayhayen** [comment]
I am also going to release 1.2, and I read this, developed the version warning feature, that will help me to tell people to make sure to use that version. Thanks for your support.
